title: Technical design docs
description: Finished technical designs for the Polkadot Products Platform
url: https://agustinustheodorus.com
baseurl: /parity-technical-design
theme: minima
markdown: kramdown
plugins:
  - jekyll-readme-index
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
exclude:
  - TEMPLATE.md
